<a href="https://colab.research.google.com/github/sabbir179/test2/blob/main/matrixPy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Gaussian elienination and finding the inverse matrix

In [1]:
import numpy as np


In [3]:
A= np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [5]:
Ainv=np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
b=np.array([5,11])
b

array([ 5, 11])

In [8]:
x=np.dot(Ainv, b)
x

array([1., 2.])

In [9]:
np.dot(A, x)

array([ 5., 11.])