<a href="https://colab.research.google.com/github/sabbir179/test2/blob/main/sciPyLinearAlgebraSVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SciPy sub package - Linear Algebra
Single value decomposition(svd)

In [1]:
# Import linalg
import numpy as np
from scipy import linalg


In [2]:
# Define matrix
numSvdArr = np.array ([[3,5,1],[9,5,7]])

In [3]:
# Find shape of ndarray which is 2X3 matrix
numSvdArr.shape

(2, 3)

In [4]:
# U(Unitary matrix)
linalg.svd(numSvdArr)

(array([[-0.37879831, -0.92547925],
        [-0.92547925,  0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [ 0.19208294, -0.82977932,  0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))