<a href="https://colab.research.google.com/github/sabbir179/test2/blob/main/VectorInPy1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Vector arithmetic**

In [2]:
import numpy as np


In [3]:
a = np.array([20,40,60])
b = np.array([10,20,30])
c = np.array([5,10,15,20])

In [4]:
a+b

array([30, 60, 90])

In [5]:
a-b

array([10, 20, 30])

In [6]:
a*b

array([ 200,  800, 1800])

In [7]:
a/b

array([2., 2., 2.])

In [8]:
scalar=2

In [9]:
list_a = [10,11,12,13,14,15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [10]:
#convert this array into nd array
list_as_arrary = np.array(list_a) 
print(list_as_arrary)

[10 11 12 13 14 15]


In [11]:
scalar*list_a

[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]

In [12]:
scalar*list_as_arrary

array([20, 22, 24, 26, 28, 30])